__Business Problem :-__ _We have to create a model which can predict the selling price of Car._

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('car data.csv')

In [3]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

__Data Preprocessing__

In [4]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [5]:
df.drop("Car_Name",axis=1,inplace=True)

In [6]:
df.head(3)

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0

In [7]:
df["Year"] = 2026-df.Year

In [8]:
df.head(3)

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,12,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,13,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,9,7.25,9.85,6900,Petrol,Dealer,Manual,0

In [9]:
df = pd.get_dummies(df,dtype=int,drop_first=True)

In [10]:
df.head()

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,12,3.35,5.59,27000,0,0,1,0,1
1,13,4.75,9.54,43000,0,1,0,0,1
2,9,7.25,9.85,6900,0,0,1,0,1
3,15,2.85,4.15,5200,0,0,1,0,1
4,12,4.60,6.87,42450,0,1,0,0,1

In [11]:
X = df.drop("Selling_Price",axis=1)
y = df.Selling_Price

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=9)

In [14]:
from sklearn.ensemble import RandomForestRegressor

In [15]:
rf = RandomForestRegressor()
rf.fit(X_train,y_train) # train
y_pred = rf.predict(X_test)  # prediction

In [16]:
from sklearn.metrics import mean_squared_error,r2_score

In [17]:
print(mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))   # testing performance

0.7694571731147546
0.9678356792809536

In [18]:
y_pred_train = rf.predict(X_train)
r2_score(y_train,y_pred_train)   # training performance

0.985692671600459

In [19]:
X_train.iloc[5].to_list()

[14.0, 5.35, 53675.0, 0.0, 0.0, 1.0, 0.0, 1.0]

In [20]:
prediction = rf.predict([[14.0, 5.35, 53675.0, 0.0, 0.0, 1.0, 0.0, 1.0]])

C:\Users\dhyan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [21]:
prediction

array([3.0255])

In [22]:
output = round(prediction[0],2)

In [23]:
"You Can Sell The Car at {}".format(output)

'You Can Sell The Car at 3.03'

In [24]:
import pickle

In [25]:
pickle.dump(rf,open("model.pkl",'wb'))